version: '3.8'

services:
  sportify-app:
    build: .
    container_name: sportify
    ports:
      - "8081:8081"   # Metro bundler
      - "19000:19000" # Expo DevTools
      - "19001:19001" # Expo DevTools
      - "19002:19002" # Expo DevTools
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.43.7  # Change to your local IP
    stdin_open: true
    tty: true
    command: npm start
